apiVersion: v1
kind: Service
metadata:
  name: udagram-frontendv2-app
  labels:
    app: udagram-frontendv2-app
spec:
  type: LoadBalancer
  selector:
    app: udagram-frontendv2-app
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100