language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

jobs:
  include:
    - stage: "API Feed"
      name: "API Feed"
      script:
        - docker --version 
        - docker build -t udagram-api-feedv2 ./udagram-api-feedv2
        - docker tag udagram-api-feedv2 antonander/udagram-api-feedv2:v2
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push antonander/udagram-api-feedv2
    - stage: "API User"
      name: "API User"
      script:
        - docker --version 
        - docker build -t udagram-api-userv2 ./udagram-api-userv2
        - docker tag udagram-api-userv2 antonander/udagram-api-userv2:v2
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push antonander/udagram-api-userv2
    - stage: "ReverseProxy"
      name: "ReverseProxy"
      script:
        - docker --version 
        - docker build -t reverseproxyv2 ./reverseproxyv2
        - docker tag reverseproxyv2 antonander/reverseproxyv2:v2
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push antonander/reverseproxyv2
    - stage: "Frontend"
      name: "Frontend"
      script:
        - docker --version 
        - docker build -t udagram-frontendv2 ./udagram-frontendv2
        - docker tag udagram-frontendv2 antonander/udagram-frontendv2:v2
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push antonander/udagram-frontendv2


