version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxyv2
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-userv2
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feedv2
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontendv2:local
