apiVersion: v1
kind: Service
metadata:
  name: reverseproxyv2-app
  labels:
    app: reverseproxyv2-app
spec:
  type: LoadBalancer
  selector:
    app: reverseproxyv2-app
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080